global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8098']
  
  - job_name: 'jenkins'
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['jenkins:8080']

  - job_name: 'mockapi'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['mockapi:8082']
  
  - job_name: 'mockapilow'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['mockapilow:8083']

  - job_name: 'mockapihigh'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['mockapihigh:8084']

rule_files:
  - mockapiHighrules.yml
  - mockapiLowrules.yml
  - mockapirules.yml
